### ISSUE TITLE
Investigate moving project to test-kitchen organization

### ISSUE THREAD

**Issue by anl** [anl/kitchen-google#16]
As suggested by @erjohnso and @mbrukman separately, this project might be better suited to live under the test-kitchen organization, particularly given my limited time to work on it currently.

**Comment by anl** [comment]
I have no idea what the mechanics of this move would be, or if they'd accept this project.  @fnichol is this something you can comment on?

**Comment by erjohnso** [comment]
Thanks @anl  - happy to help out a bit if it's needed.

**Comment by mbrukman** [comment]
Ping @fnichol (cc: @someara) — what are your thoughts on moving this module to the Test Kitchen org?

**Comment by someara** [comment]
Fine by me. :+1:

**Comment by mbrukman** [comment]
@anl, could you please give @someara write access to your repo so that he can [transfer the repo](https://help.github.com/articles/transferring-a-repository/)?

**Comment by anl** [comment]
Hmm, I only saw an option to make @someara a "collaborator" - is that enough to transfer the repo, or did I miss the correct setting?

**Comment by mbrukman** [comment]
@anl — I don't think "collaborator" permissions are sufficient, because the person doing the transfer needs to have "delete" permissions on this repository (anl/kitchen-gce) in order to do the transfer and let GitHub set up the right forwarding. However, per the [permissions doc](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#owner-access-on-a-repository-owned-by-a-user-account), only the "owner" of a repo has "delete" permissions, and a user repo can only have a single owner, which is @anl so @someara can't be added as "owner".

The [transferring a repo doc](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) that @anl is citing suggests a way forward. The only other approach I can see here would be a more complex multi-step transfer:

* user -> user (@anl -> @someara), followed by
* user -> org (@someara -> Test Kitchen)

but I would recommend the simpler direct approach of user -> org if @someara can create a temporary single-user admin group within Test Kitchen and let @anl make the transfer in one step.

**Comment by someara** [comment]
Hey everyone... I just cleared this with Fletcher...

If you go into "settings" there's a "transfer ownership" option in the
Danger Zone.

I've found it easier to bounce things through personal repos rather than
orgs, so if somebody wants to transfer it to someara, I'll make sure it
finds it way home to test-kitchen

-s

**Comment by fnichol** [comment]
Ok, (re)found this, we're going to make this happen :+1:

**Comment by mbrukman** [comment]
@anl, looks like it's all up to you now: please transfer the ownership of the repo to @someara to start the process.

Also, as we are making the move, can we please rename it from `kitchen-gce` to `kitchen-google`? Thanks!

**Comment by mbrukman** [comment]
Ping, @anl?

**Comment by anl** [comment]
Transferring the repo now; I'll leave the name change to be done post-transfer.

**Comment by anl** [comment]
Hmm,  someara/kitchen-gce already exists, so the transfer is blocked.  Probably an old fork?

**Comment by mbrukman** [comment]
@anl - looks like an easy way to work around it would be to rename the repo locally within your account to `kitchen-google` and then transfer it to @someara.

I don't think it matters whether it's renamed now or later; GitHub will set up the forwarding for the chain of modifications anyway.

**Comment by anl** [comment]
Renamed to kitchen-google; "@someara already has a repository in the anl/kitchen-google network".

**Comment by someara** [comment]
I deleted my fork. Try again

**Comment by someara** [comment]
ping!

**Comment by someara** [comment]
@anl can you try the transferring the repo again?

**Comment by anl** [comment]
Apologies for the delay - transferring now.

**Comment by mbrukman** [comment]
Thank you, @anl! @someara, please let us know when this repo has made its way into the Test Kitchen org.

**Comment by erjohnso** [comment]
:dancers: Thank you @anl!

**Comment by someara** [comment]
... and we're live!

https://github.com/test-kitchen/kitchen-google

Thanks everyone!

-s

**Comment by someara** [comment]
What are everyone's github ID again?

I'm going to make a kitchen-google-admins team for the project and put
everyone in it.

-s

**Comment by erjohnso** [comment]
Awesome, thank you Sean!  On the Google side, please include @erjohnso, @paulrossman, and @mbrukman.

**Comment by mbrukman** [comment]
Thank you, @someara! Great to see this happen.
